### ISSUE TITLE
[NPC]#18880/18130/18131/18285/20196/21901 should spawn with 0 mana

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2604]
**Description**: 
Following NPCs start with a full mana bar, but should start with an empty one.

- [ ] [[NPC]Marshfang Slicer#18131](https://www.wowhead.com/npc=18131/marshfang-slicer) - [Video here](https://www.youtube.com/watch?v=bzLYStDy7rA&feature=youtu.be&t=31s)

- [ ] [[NPC]Marshfang Ripper#18130](https://www.wowhead.com/npc=18130/marshfang-ripper) - [Video here](https://www.youtube.com/watch?v=bzLYStDy7rA&feature=youtu.be&t=31s)

- [ ] [[NPC]"Count" Ungula#18285](https://www.wowhead.com/npc=18285/count-ungula) - [Video here](https://www.youtube.com/watch?v=GqvshZ9ztLc&feature=youtu.be&t=5s)

- [ ] [[NPC]Bloodthirsty Marshfang#20196](https://www.wowhead.com/npc=20196/bloodthirsty-marshfang) - [Comment here](https://www.wowhead.com/npc=20196/bloodthirsty-marshfang#comments:id=940824)

- [ ] [[NPC]Nether Ray#18880](https://www.wowhead.com/npc=18880/nether-ray#comments) - [Video here](https://youtu.be/NVO4QnH2FuE?t=29)

- [ ] [[NPC]Netherskate#21901](https://www.wowhead.com/npc=21901/netherskate#screenshots) - [Video here](https://youtu.be/ty1lwYNqZ8Q?t=1)

**Current behaviour**:
Starts with full mana.

**Expected behaviour**: 
Start with 0 mana.

**Server Revision**: 
2851

**Comment by Kiperr** [comment]
-- Creature Nether Ray 18880 SAI
SET @ENTRY := 18880;
UPDATE creature_template SET AIName="SmartAI" WHERE entry= @ENTRY;
DELETE FROM smart_scripts WHERE entry=@ENTRY AND script_source_type=0;
INSERT INTO smart_scripts (entry, script_source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, event_param6, event_param7, event_param8, event_cooldown_min, event_cooldown_max, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, action_param7, action_param8, source_type, source_param1, source_param2, source_param3, source_condition_id, target_type, target_param1, target_param2, target_param3, target_condition_id, target_x, target_y, target_z, target_o, comment) VALUES
(@ENTRY, 0, 3, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 102, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "On respawn  - Self: Set mana 0 // ");

**Comment by Kiperr** [comment]
Need add core feature like "HealthRegen" to mana.

**Comment by ZymNW** [comment]
This is still the case that mobs spawn with full mana, mob behavior should be to drain mana until they have enough to cast their Nether Shock ability but on aggro they use the shock, which makes them much stronger than intended having access to their instant cast nuke with attached cc at all times.

**Comment by bidaumm** [comment]
still the case as per #7412

**Comment by Wolffenstein** [comment]
Fixed in rev 3660.

**Comment by Godmatik** [comment]
Need to apply the same status to "Mana Shifters" in Ghostlands, they start with full mana but should start with 0.

https://www.wowhead.com/wotlk/npc=16310/mana-shifter#comments
