### ISSUE TITLE
[Item] Meta Gem Fixes

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3369]
**Description**: 
Meta gems had different requirements to activate, more information in their specific issues. Closing the single issues to make it a bit more clean
- [ ] Bracing Earthstorm Diamond#25897 - https://github.com/Atlantiss/NetherwingBugtracker/issues/3104
- [ ] Tenacious Earthstorm Diamond#25898 - https://github.com/Atlantiss/NetherwingBugtracker/issues/3103
- [ ] Powerful Earthstorm Diamond#25896 - https://github.com/Atlantiss/NetherwingBugtracker/issues/3102
- [ ] Brutal Earthstorm Diamond#25899 - https://github.com/Atlantiss/NetherwingBugtracker/issues/3101
- [ ] Destructive Skyfire Diamond#25890 - https://github.com/Atlantiss/NetherwingBugtracker/issues/3100
- [ ] Insightful Earthstorm Diamond#25901 - https://github.com/Atlantiss/NetherwingBugtracker/issues/3099

**Current behaviour**:
2.4.3 requirements

**Expected behaviour**: 
2.0 requirements

**Server Revision**: 
2407

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Manaci** [comment]
Reopened for future usage

**Comment by Manaci** [comment]
#3115 #5903

**Comment by Godmatik** [comment]
Not using 2.0 stats/procs for items any longer - closing
