### ISSUE TITLE
[NPC][Misc]Collection of mobs lacking "run away"-emote/mechanic & others

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3437]
**Description**: 
If nothing is specified it's simply lacking "run away"-emote & mechanic.

**Zone: Zangarmarsh**
- [ ] [[NPC]Umbrafen Witchdoctor#20115](https://www.wowhead.com/npc=18079/umbrafen-seer) - [Video here](https://youtu.be/LgVaXyHzJPg?t=184) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2128

- [ ] [[NPC]Umbrafen Oracle#18077](https://www.wowhead.com/npc=18077/umbrafen-oracle) - [Video here](https://youtu.be/LgVaXyHzJPg?t=184) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2127

- [ ] [[NPC]Umbrafen Seer#18079](https://www.wowhead.com/npc=18079/umbrafen-seer) - [Video here](https://youtu.be/LgVaXyHzJPg?t=184) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2126

- [ ] [[NPC]Daggerfen Assassin#18116](https://www.wowhead.com/npc=18116/daggerfen-assassin) lack "crushes a vial of green gas." on [[Spell]Toxic Fumes#35204](https://www.wowhead.com/spell=35204/toxic-fumes) cast - [Video here](https://youtu.be/4tPZZTXhpqA?t=85) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2295 casts too frequent: https://github.com/Atlantiss/NetherwingBugtracker/issues/2296

---

**Zone: Black Rock Depths(Dungeon)**
- [ ] [[NPC]Anvilrage Warden#8890](https://www.wowhead.com/npc=8890/anvilrage-warden#comments) - [Video here](https://youtu.be/d0NFxB3qOEg?t=60) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2080

- [ ] [[NPC]Twilight's Hammer Torturer#8912](https://www.wowhead.com/npc=8912/twilights-hammer-torturer#comments) - [Video here](https://youtu.be/d0NFxB3qOEg?t=53) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2078

- [ ] [[NPC]Anvilrage Guardsman#8891](https://www.wowhead.com/npc=8891/anvilrage-guardsman) -   [Video here](https://www.youtube.com/watch?v=nwOyPe6efA4) -https://github.com/Atlantiss/NetherwingBugtracker/issues/2069

- [ ] [[NPC]Anvilrage Footman#8892](https://www.wowhead.com/npc=8892/anvilrage-footman#comments) - [Video here](https://www.youtube.com/watch?v=nwOyPe6efA4) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2068

---

**Zone: Nagrand**
- [ ] [[NPC]Rumbling Earth-Heart#22313](https://www.wowhead.com/npc=22313/rumbling-earth-heart#comments) frenzy! -> enrage! - [Video here](https://youtu.be/yBAY9lBPYHk?t=66) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2973

---

In addition the mechanic itself is slightly off, making the game easier: https://github.com/Atlantiss/NetherwingBugtracker/issues/3273

**Current behaviour**:
Currently lacking this mechanic

**Expected behaviour**: 
Expected to have it

**Server Revision**: 
2431

**Comment by wtRCH** [comment]
I am pinning it, becuase I hope you fill this issue with more reports.

**Comment by Tenoutoften** [comment]
Sure if more is found

**Comment by Evolvee** [comment]
rev 2468
