### ISSUE TITLE
[Loot]Last bosses in heroics should drop 2 blue items

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3438]
**Description**: 
- [ ] [[NPC]Epoch Hunter#20531](https://db.excalibur.ws/?npc=20531) - [Video here](https://youtu.be/6lOWgKhAMvU?t=434) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2997
- [ ] [[NPC]The Black Stalker#20184](https://db.excalibur.ws/?npc=20184) -[Video here](https://youtu.be/GtFAfZBLsXU?t=177) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2977
- [ ] [[NPC]Warlord Kalithresh#20633](https://db.excalibur.ws/?npc=20633) - [Video here](https://youtu.be/ZfTV61jJyQY?t=387) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2982
- [ ] [[NPC]Warcheif Kargath Bladefist#20597](https://db.excalibur.ws/?npc=20597) - [Video here](https://youtu.be/PvMfIQFPPI8?t=475) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2682
- [ ] [[NPC]Pathaleon the Calculator#21537](https://db.excalibur.ws/?npc=21537) - [Video here](https://youtu.be/eMDFtiD0RlI?t=99)

---

**Not confirmed**
* [[NPC]Quagmirran#19894](https://db.excalibur.ws/?npc=19894) - [Video here](https://youtu.be/tMaPL3Aj9k8?t=542)

---

**[Patch 2.1.0](http://wowwiki.wikia.com/wiki/Patch_2.1.0)**
* Heroic difficulty instances end bosses will now always drop an epic item, in addition all bosses in Heroic difficulty instances will have a chance to drop an epic gem!

**Current behaviour**:
Only drop 1 blue

**Expected behaviour**:
Drop 2 blue

**Server Revision**: 
2431

**Comment by aresbrutus** [comment]
And post 2.1 it should be 1 guaranteed epic and 1 guaranteed blue I believe.

**Comment by Tenoutoften** [comment]
Some of these videos are after 2.1 and still drop 2 blues in addition to the 1 epic, but I edited in the patch notes from 2.1 w/ link

**Comment by ircfelix** [comment]
Search my videos archive for pre nerf heroic bosses: https://docs.google.com/document/d/1POfMSx5ZO6Y1RX88znSghfeGyeXwT4Jxqzk6N_wxhPc/edit?usp=drivesdk

Especially this resource is packed with pre nerf runs, orten with people wearing t3: https://www.youtube.com/user/madoqa/videos

**Comment by Wolffenstein** [comment]
Fixed in rev 2453.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3530 recheck?

**Comment by killablink** [comment]
Still not fixed, got 1 loot from heroic slaves pens + nether

**Comment by knasen88** [comment]
SCUFFED loottable [https://i.imgur.com/9dfm9So.jpg](url)
reopen, rev 2647

**Comment by knasen88** [comment]
https://i.imgur.com/tWxqfk7.jpg
again
