### ISSUE TITLE
[Megathread][Quest] Issues with Escort Quests(React state, Faction, Interaction, Buff reset, Pathing)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3678]
**Description**: 
Several escort quests & NPCs share the same issues. This report isn't complete and could use some additional videos.

<details>
  <summary>1) Can't interact(Buff & Heals) with escort NPC</summary>
  
- [x] [[NPC]Prospector Remtravel#2917](https://www.wowhead.com/npc=2917/prospector-remtravel) - [Video here](https://www.youtube.com/watch?v=LaeD5gtM_68&feature=youtu.be) - [Quest#731](https://www.wowhead.com/quest=731/the-absent-minded-prospector)
- [x] [[NPC]"Stinky" Ignatz#4880](https://www.wowhead.com/npc=4880/stinky-ignatz) - https://github.com/Atlantiss/NetherwingBugtracker/issues/1289 - [Video here](https://youtu.be/aE5VRy8tzso?t=17) - [Quest#1270](https://www.wowhead.com/quest=1270/stinkys-escape) (Invalid)
- [x] [[NPC]Kerlonian Evershade#11218](https://www.wowhead.com/npc=11218/kerlonian-evershade) - [Video here](https://www.youtube.com/watch?v=P52wo9tAhI8&feature=youtu.be) - [Quest#5321](https://www.wowhead.com/quest=5321/the-sleeper-has-awakened) (Invalid)
- [x] [[NPC]Ruul Snowhoof#12818](https://www.wowhead.com/npc=12818/ruul-snowhoof) - [Video here](https://www.youtube.com/watch?v=CaioPQx8cLY&feature=youtu.be) - [Quest#6482](https://www.wowhead.com/quest=6482/freedom-to-ruul#comments:id=142549)
- [x] [[NPC]Maxx A. Million Mk. V#19589](https://www.wowhead.com/npc=19589/maxx-a-million-mk-v) - [Video here](https://www.youtube.com/watch?v=URry8SUlboo&feature=youtu.be) - [Quest#10191](https://www.wowhead.com/quest=10191/mark-v-is-alive)
- [x] [[NPC]Drijya#20281](https://www.wowhead.com/npc=20281/drijya) - [Video here](https://www.youtube.com/watch?v=SAfOFiEL_ks&feature=youtu.be) - [Quest#10310](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate#comments)
- [x] [[NPC]Bessy#20415](https://www.wowhead.com/npc=20415/bessy) - [Video here](https://www.youtube.com/watch?v=jdAf13s4zBU&feature=youtu.be) - [Quest#10337](https://www.wowhead.com/quest=10337/when-the-cows-come-home)
- [x] [[NPC]Akuno#22377](https://www.wowhead.com/npc=22377/akuno) - [Video here](https://www.youtube.com/watch?v=mtfSG0Id1FM&feature=youtu.be) -  [Quest#10887](https://www.wowhead.com/quest=10887/escaping-the-tomb) (Invalid)

</details>

---

<details>
  <summary>2) Escort NPC resets buffs every combat reset</summary>
  
- [x] [[NPC]Corporal Keeshan#349](https://www.wowhead.com/npc=349/corporal-keeshan) - [Video here](https://youtu.be/8YU8ZBMJ5ko?t=68) - [Quest#219](https://www.wowhead.com/quest=219/missing-in-action)
- [x] [[NPC]Therylune#3584](https://www.wowhead.com/npc=3584/therylune) - [Video here](https://www.youtube.com/watch?v=111kiXElH0c) - [Quest#945](https://www.wowhead.com/quest=945/therylunes-escape) 
- [x] [[NPC]Rin'ji#7780](https://www.wowhead.com/npc=7780/rinji) - https://github.com/Atlantiss/NetherwingBugtracker/issues/1665 - [Video here](https://www.youtube.com/watch?v=mIR0ic-CorQ&feature=youtu.be) - [Quest#2742](https://www.wowhead.com/quest=2742/rinji-is-trapped)
- [x] [[NPC]Kaya Flathoof#11856](https://www.wowhead.com/npc=11856/kaya-flathoof) - [Video here](https://youtu.be/KVIz55hf6k4) - [Quest#6523](https://www.wowhead.com/quest=6523/protect-kaya)
- [ ] [[NPC]Thrall#17876](https://www.wowhead.com/npc=17876/thrall) & [[NPC]Thrall#20548](https://db.excalibur.ws/?npc=20548) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2992 - [Quest#10284](https://www.wowhead.com/quest=10284/escape-from-durnholde)
- [x] [[NPC]Demolitionist Legoso#17982](https://www.wowhead.com/npc=17982/demolitionist-legoso) - [Video here](https://www.youtube.com/watch?v=TVV0Q5rq3sw) - [Quest#9759](https://www.wowhead.com/quest=9759/ending-their-world) 

</details>

---

<details>
  <summary>3) Escort NPC is on passive-mode(Doesn't react when the player is nearby and engaged in combat/ Some of them ignores mobs striking them)</summary>
  
- [x] [[NPC]The Defias Traitor#467](https://www.wowhead.com/npc=467/the-defias-traitor) - [Video here](https://youtu.be/Ddg0Y2JLp70?t=76) - [Quest#155](https://www.wowhead.com/quest=155/the-defias-brotherhood)
- [x] [[NPC]"Stinky" Ignatz#4880](https://www.wowhead.com/npc=4880/stinky-ignatz) - [Video here](https://www.youtube.com/watch?v=aE5VRy8tzso&feature=youtu.be) - [Quest#1270](https://www.wowhead.com/quest=1270/stinkys-escape) - https://github.com/Atlantiss/NetherwingBugtracker/issues/1287 (Invalid)
- [x] [[NPC]Mag'har Captive#18210](https://www.wowhead.com/npc=18210/maghar-captive) - [Quest#9868](https://www.wowhead.com/quest=9868/the-totem-of-kardash)
- [x] [[NPC]Kurenai Captive#18209](https://www.wowhead.com/npc=18209/kurenai-captive) - [Quest#9879](https://www.wowhead.com/quest=9879/the-totem-of-kardash) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2264
- [x] [[NPC]Prospector Remtravel#2917](https://www.wowhead.com/npc=2917/prospector-remtravel) - [Video here](https://www.youtube.com/watch?v=w1EoDo2pi_w&feature=youtu.be) - [Quest#731](https://www.wowhead.com/quest=731/the-absent-minded-prospector) - https://github.com/Atlantiss/NetherwingBugtracker/issues/504
- [x] [[NPC]Maxx A. Million Mk. V#19589](https://www.wowhead.com/npc=19589/maxx-a-million-mk-v) - [Quest#10191](https://www.wowhead.com/quest=10191/mark-v-is-alive) - https://github.com/Atlantiss/NetherwingBugtracker/issues/2265
- [x] [[NPC]Bessy#20415](https://www.wowhead.com/npc=20415/bessy) - [Video here](https://www.youtube.com/watch?v=d1BlKj9BoOc&feature=youtu.be) - [Quest#10337](https://www.wowhead.com/quest=10337/when-the-cows-come-home)
- [x] [[NPC]Ranshalla#10300](https://www.wowhead.com/npc=10300/ranshalla) - [Quest#4901](https://www.wowhead.com/quest=4901/guardians-of-the-altar) - https://github.com/Atlantiss/NetherwingBugtracker/issues/1098
- [x] [[NPC]The Defias Traitor#467](https://www.wowhead.com/npc=467/the-defias-traitor) - [Video here](https://www.youtube.com/watch?v=4yGTJV9-MEk) - [Quest#155](https://www.wowhead.com/quest=155/the-defias-brotherhood) - https://github.com/Atlantiss/NetherwingBugtracker/issues/267
- [x] [[NPC]Demolitionist Legoso#17982](https://www.wowhead.com/npc=17982/demolitionist-legoso) - [Quest#9759](https://www.wowhead.com/quest=9759/ending-their-world) - https://github.com/Atlantiss/NetherwingBugtracker/issues/343- Can't reproduce need research  - Other minor issues listed [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/3343) 
- [x] [[NPC]Ranger Lilatha#16295](https://www.wowhead.com/npc=16295/ranger-lilatha) - [Quest#9212](https://www.wowhead.com/quest=9212/escape-from-the-catacombs) - https://github.com/Atlantiss/NetherwingBugtracker/issues/323 - Can't reproduce need research

</details>

---

<details>
  <summary>4) Wrong faction, escort NPC doesn't aggro any mobs, but walks through them:</summary>
  
- [x] [[NPC]Rin'ji#7780](https://www.wowhead.com/npc=7780/rinji) - [Video here](https://www.youtube.com/watch?v=bRNuJOodzE4&feature=youtu.be) - [Quest#2742](https://www.wowhead.com/quest=2742/rinji-is-trapped)
- [x] [[NPC]Homing Robot OOX-17/TN#7784](https://www.wowhead.com/npc=7784/homing-robot-oox-17-tn) - [Video here](https://youtu.be/D3QRwGcV8S0?t=75) - [Quest#648](https://www.wowhead.com/quest=648/rescue-oox-17-tn) - https://github.com/Atlantiss/NetherwingBugtracker/issues/1114
- [x] [[NPC]Homing Robot OOX-09/HL#7806](https://www.wowhead.com/npc=7806/homing-robot-oox-09-hl) - [Quest#836](https://www.wowhead.com/quest=836/rescue-oox-09-hl) - https://github.com/Atlantiss/NetherwingBugtracker/issues/970
- [x] [[NPC]Homing Robot OOX-22/FE](https://www.wowhead.com/npc=7807/homing-robot-oox-22-fe) - [Video here](https://clips.twitch.tv/UglyObliviousPizzaKevinTurtle) - [Quest#2767](https://www.wowhead.com/quest=2767/rescue-oox-22-fe) - https://github.com/Atlantiss/NetherwingBugtracker/issues/939
</details>

---

<details>
  <summary>5) Not all party members get credit:</summary>
  
- [x] [[NPC]"Stinky" Ignatz#4880](https://www.wowhead.com/npc=4880/stinky-ignatz) - https://github.com/Atlantiss/NetherwingBugtracker/issues/1426 - [Quest#1222](https://www.wowhead.com/quest=1270/stinkys-escape)
- [x] Likely affected as well [[NPC]"Stinky" Ignatz#4880](https://www.wowhead.com/npc=4880/stinky-ignatz) - [Quest#1270](https://www.wowhead.com/quest=1222/stinkys-escape)
</details>

---

<details>
  <summary>6) Specific issues for quests/NPCs</summary>
  
- [ ] [Quest#2767](https://www.wowhead.com/quest=2767/rescue-oox-22-fe) - [[NPC]Homing Robot OOX-22/FE](https://www.wowhead.com/npc=7807/homing-robot-oox-22-fe) - [Video here](https://clips.twitch.tv/UglyObliviousPizzaKevinTurtle) - https://github.com/Atlantiss/NetherwingBugtracker/issues/939 - Currently in Cataclysm version
- [ ] [Quest#6482](https://www.wowhead.com/quest=6482/freedom-to-ruul#comments:id=142549) - Quest should end when [[NPC]Ruul Snowhoof#12818](https://www.wowhead.com/npc=12818/ruul-snowhoof) is outside of the camp. Currently ends outside of cave. - [AtlantissTBCBT#1943](https://github.com/Atlantiss/AtlantissTBCBT/issues/1943) - [Wowhead comment, Patch: 2.1.3](https://www.wowhead.com/quest=6482/freedom-to-ruul#comments:id=142549)
- [ ] [Quest#9212](https://www.wowhead.com/quest=9212/escape-from-the-catacombs) - [[NPC]Ranger Lilatha#16295](https://www.wowhead.com/npc=16295/ranger-lilatha) got slight error in path - [Video here](https://youtu.be/U5jXV7cPebA?t=170)
- [ ] [Quest#9212](https://www.wowhead.com/quest=9212/escape-from-the-catacombs) - [[NPC]Ranger Lilatha#16295](https://www.wowhead.com/npc=16295/ranger-lilatha) - The mobs spawned by the event are immobilized until struck - [Video here](https://youtu.be/U5jXV7cPebA?t=111) - https://github.com/Atlantiss/NetherwingBugtracker/issues/323 / https://github.com/Atlantiss/NetherwingBugtracker/issues/706
- [ ] [Quest#9868](https://www.wowhead.com/quest=9868/the-totem-of-kardash) - [[NPC]Mag'har Captive#18210](https://www.wowhead.com/npc=18210/maghar-captive) - Able to accept quest once guards are engaged rather than dead.
- [ ] [Quest#9879](https://www.wowhead.com/quest=9879/the-totem-of-kardash) - [[NPC]Kurenai Captive#18209](https://www.wowhead.com/npc=18209/kurenai-captive) - Able to accept quest once guards are engaged rather than dead.
- [ ] [Quest#9868](https://www.wowhead.com/quest=9868/the-totem-of-kardash) - [[NPC]Mag'har Captive#18210](https://www.wowhead.com/npc=18210/maghar-captive) - Several errors in path.
- [ ] [Quest#9879](https://www.wowhead.com/quest=9879/the-totem-of-kardash) - [[NPC]Kurenai Captive#18209](https://www.wowhead.com/npc=18209/kurenai-captive) - error in path(Likely several, need test)
- [ ] [Quest#10191](https://www.wowhead.com/quest=10191/mark-v-is-alive) error in path, happens after a bit after you cross the bridge.
- [ ] [Quest#10310](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate) - [[NPC]Drijya#20281](https://www.wowhead.com/npc=20281/drijya) should instantly fail if [NPC#20404, ID: 1,2,3,4](https://www.wowhead.com/npc=20404/warp-gate-engineer) isn't up. - [Comment](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate#comments:id=24736:reply=2601)
- [ ] [Quest#10310](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate) - Spawned mobs should attack [[NPC]Drijya#20281](https://www.wowhead.com/npc=20281/drijya) by default https://github.com/Atlantiss/NetherwingBugtracker/issues/2616 - [NW Vid, goes for player](https://youtu.be/KjJ3tMcFh88?t=169) - [Comment](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate#comments:id=290219)
- [ ] [Quest#10310](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate) - [[NPC]Drijya#20281](https://www.wowhead.com/npc=20281/drijya) kills himself after completed quest, shouldn't - [Retail vid](https://youtu.be/6hayqrW5SSk?t=321)
- [ ] [Quest#10337](https://www.wowhead.com/quest=10337/when-the-cows-come-home) - [[NPC]Bessy#20415](https://www.wowhead.com/npc=20415/bessy) will teleport, I think it has a potential of two teleports [1# TP](https://youtu.be/d1BlKj9BoOc?t=91) this TP brings it 30-40 yards forward. [2# TP](https://youtu.be/d1BlKj9BoOc?t=109) this TP brings it 60 yards away. Given that a player sometimes is 30 yards behind the escort NPC this will often force a failed due to range limitation.
- [ ] [Quest#10425](https://www.wowhead.com/quest=10425/escape-from-the-staging-grounds) missing opening RP - details and evidence:https://github.com/Atlantiss/NetherwingBugtracker/issues/3408
</details>

---

<details>
  <summary>Quests/NPCs affected</summary>
  
  ---
[[Quest]The Defias Brotherhood#155](https://www.wowhead.com/quest=155/the-defias-brotherhood)
[[Quest]Missing in Action#219](https://www.wowhead.com/quest=219/missing-in-action)
[[Quest]Rescue OOX-17TN!#648](https://www.wowhead.com/quest=648/rescue-oox-17-tn)
[[Quest]The Absent Minded Prospector#731](https://www.wowhead.com/quest=731/the-absent-minded-prospector)
[[Quest]Rescue OOX-09/HL!#836](https://www.wowhead.com/quest=836/rescue-oox-09-hl)
[[Quest]Therylune's Escape#945](https://www.wowhead.com/quest=945/therylunes-escape)
[[Quest]Stinky's Escape#1222](https://www.wowhead.com/quest=1270/stinkys-escape)
[[Quest]Rescue OOX-22/FE!#2767](https://www.wowhead.com/quest=2767/rescue-oox-22-fe)
[[Quest]Rin'ji is Trapped!#2742](https://www.wowhead.com/quest=2742/rinji-is-trapped)
[[Quest]Guardians of the Altar#4901](https://www.wowhead.com/quest=4901/guardians-of-the-altar)
[[Quest]The Sleeper Has Awakened#5321](https://www.wowhead.com/quest=5321/the-sleeper-has-awakened)
[[Quest]Freedom to Ruul#6482](https://www.wowhead.com/quest=6482/freedom-to-ruul#comments:id=142549)
[[Quest]Protect Kaya#6523](https://www.wowhead.com/quest=6523/protect-kaya)
[[Quest]Escape from the Catacombs#9212](https://www.wowhead.com/quest=9212/escape-from-the-catacombs)
[[Quest]Ending Their World#9759](https://www.wowhead.com/quest=9759/ending-their-world)
[[Quest]The totem of Kardash#9868](https://www.wowhead.com/quest=9868/the-totem-of-kardash)
[[Quest]The totem of Kardash#9879](https://www.wowhead.com/quest=9879/the-totem-of-kardash)
[[Quest]Mark V is Alive!#10191](https://www.wowhead.com/quest=10191/mark-v-is-alive)
[[Quest]Escape from Durnholde#10284](https://www.wowhead.com/quest=10284/escape-from-durnholde)
[[Quest]Sabotage the Warp-Gate!#10310](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate#comments)
[[Quest]When the Cows Come Home#10337](https://www.wowhead.com/quest=10337/when-the-cows-come-home)
[[Quest]Escape from the staging grounds#10425](https://www.wowhead.com/quest=10425/escape-from-the-staging-grounds)
[[Quest]Escaping the Tomb#10887](https://www.wowhead.com/quest=10887/escaping-the-tomb) 

  ---

</details>

---

https://github.com/Atlantiss/NetherwingBugtracker/issues/267#issuecomment-423945600
![](https://i.gyazo.com/7a54d273ac923d0ef110ff1f2d0fe735.png)

**Server Revision**: 
Various

**Comment by Tenoutoften** [comment]
Stinky for alliance didn't react when players had mobs on when I did it today

**Comment by Tenoutoften** [comment]
![](https://i.gyazo.com/1d5819529689c688efe3864ed6ff3cb3.png)
Hinterland escort has a stuck owlkin

**Comment by pelekon** [comment]
@Tenoutoften cuz Stinky shouldn't react, he should only defend himself when mobs attack him

**Comment by Jalapan** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4378

https://github.com/Atlantiss/NetherwingBugtracker/issues/4358

**Comment by RyadaProductions** [comment]
"Stinky" Ignatz broke completely, has been standing still for 15 minutes after accepting the quest.

**Comment by Godmatik** [comment]
I will assume all the checkmarked issues are resolved.
Need to review all of the ones listed under 6)

**Comment by Dailybg** [comment]
https://imgur.com/a/7Ytouwy Drijya seems not in his place and I cannot talk to him.
