### ISSUE TITLE
[Outlands][Quest]A collection of quests in critical condition(Non Completable / Almost non completable)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4207]
**Description/Current behaviour**: 

**Very Important**

[Shadowmoon Valley]
- [x] Teron Gorefiend quest can't be completed, it's one of the most important quests because it gives a very good helm for a lot of classes: https://github.com/Atlantiss/NetherwingBugtracker/issues/2640 / https://github.com/Atlantiss/NetherwingBugtracker/issues/2544

[Netherstorm]
- [ ] Deathblow to the Legion, I believe this quest is completable, but it is incredibly over tuned and gives important items: https://github.com/Atlantiss/NetherwingBugtracker/issues/2615 / https://github.com/Atlantiss/NetherwingBugtracker/issues/2614 / https://github.com/Atlantiss/NetherwingBugtracker/issues/2613
![](https://i.gyazo.com/33b0060c4293d2212efeb02a1f5e5008.png)
- [ ] Dimensius has a long respawn timer and only the player talking with the captain to start the escort will get their talk-objective complete. The adds of the captain don't engage in the main fight. Spawned adds do nothing. https://github.com/Atlantiss/NetherwingBugtracker/issues/2511

**Less important:**
[Nagrand]
- [x] Corki cages don't close, I think this might be limited to 2 of them and not all 3. This quest can be completed, but you need server restart / crash to reset the cages: https://github.com/Atlantiss/NetherwingBugtracker/issues/2528 / https://github.com/Atlantiss/NetherwingBugtracker/issues/4099

[Netherstorm]
- [x] Talbuks don't get un-tagged, requires server restart/crash to complete: https://github.com/Atlantiss/NetherwingBugtracker/issues/2666
- [ ] Lashers don't get unmutated. Requires players to clear other peoples mobs to reset their status. https://github.com/Atlantiss/NetherwingBugtracker/issues/2665

[Karazhan]
- [x] The Master's Terrace freezes the raid when the book is used. Quest completion is granted however.

**Server Revision**: 
2625

**Comment by Bzmode** [comment]
Don't forget #2246

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4330

**Comment by Tenoutoften** [comment]
@RealZwox I usually make a report for each bug, but I asked if they would like it if I gathered the quests it critical condition into one report and they said yes, so that's why I did it. I can edit in check boxes.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4417

**Comment by Jalapan** [comment]
Server rev 2684 should have teron gorefiend quest fixed and also corki cages fixed

**Comment by lhevraz** [comment]
Deathblow to the legion still undoable. We can't even launch the event.

**Comment by Manaci** [comment]
All are fixed
